### ISSUE TITLE
Verify macOS Sierra compatibility

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#129]
Currently we are unaware of what the operating system name of macOS Sierra is when exposed through Java. This may break our OS checks.

**Comment by zhedar** [comment]
First quick test in macOS Sierra public beta shows, that it doesn't break anything. `System.getProperty("os.name")` still returns `Mac OS X`, which is nice, because it doesn't break applications, but may be confusing and subject to change in the next versions.

Seems like I overreacted by thinking this would break things ;)
