### ISSUE TITLE
Create multi-provider GUI

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#13]
As per the pull request from @christianhood, we should be able to support multiple providers. However, this needs to be integrated into the GUI, requiring changes to the FileHandler layer.
See 39a61e2e3722b9fb6dc65fb046f603c5913a4c64 for more details.

**Comment by christianhood** [comment]
I thought it might be a good idea to discuss things regarding the GUI and internal architecture requirements for implementing multiple providers in here instead of in the pull request. 

I've made some changes to allow for turning providers on and off on the code side (ccfdfe1c7b94506e9fdf59d1a96520ab3d00544d), it would just require some UI changes to be usable. I had to change the way Provider.getAll() worked so that it didn't create a new list every time, not sure if that's okay or not so I didn't want to create a pull request and figured I'd let you take a look at it first.

**Comment by eivindveg** [comment]
I'm seeing unconfirmed reports as well as indications that Hero.GG actually hasn't parsed replays for a long time. Freezing this issue until we have confirmation Hero.GG is running properly.

**Comment by christianhood** [comment]
I've noticed that it takes a while for replays to appear now, like two days ago the latest replays of mine were from about the 9th and then yesterday my replays up to the 15th appeared on there. Not sure exactly what's going on but they seem to be going on there still, just slowly.

**Comment by eivindveg** [comment]
As per [a Strawpoll](http://strawpoll.me/5814678/r), most users don't want multiple providers. Closing this.
