### ISSUE TITLE
Brew still on version 2.1.1

### ISSUE THREAD

**Issue by chasingtheflow** [eivindveg/HotSUploader#146]
Everytime the app opens it suggests updating to 2.1.3, but I installed from Brew (as the docs suggest doing) and I'd prefer to continue to use brew to update it. However the brew cask is still on 2.1.1

**Comment by zhedar** [comment]
We are using Homebrew Cask and 2.1.3 should be available through its repo.
However, it seems it doesn't update like you would it expect it to. I suggest you try `brew cask reinstall hots-replay-uploader`, it should pull the newest version.

**Comment by zhedar** [comment]
The problem is with the way casks (those are binary-supplied packages) are updated. They don't generally upgrade with all your other taps, it seems like you have to do that manually.

To simplify that process, you could [tap cask-upgrade](http://stackoverflow.com/a/39612419/1644440) and incorporate `brew cu` into your update script/alias. I normally use that to update and upgrade all of my taps with as little keystrokes as possible.
Installation and example taken from the above linked SO answer:
```
brew tap buo/cask-upgrade
brew update
brew cu
```

**Comment by chasingtheflow** [comment]
Thanks! 

I had no idea that was required for casks. I'm glad I asked as I've now found I had 5 or 6 that were out of date and I had assumed they were updating via brew. I have an update alias `brewup` which I've now edited to include this.

👍

**Comment by eivindveg** [comment]
Should we add a note for this in the release note template?

**Comment by chasingtheflow** [comment]
It might be nice to have it mentioned in the readme as many people may not be aware that casks are not upgraded the same way as typical brew installed apps. It would have saved me here anyway.

**Comment by zhedar** [comment]
I agree. This is indeed a common pitfall, because there isn't really native way to upgrade casks yet. It was discussed for a long time, but somehow isn't happening :( We should probably add it to the readme and the release notes. It probably won't hurt much.

**Comment by eivindveg** [comment]
Could add an Upgrading section to the readme, with sub-sections for each platform, then link to this section in the release notes.
