### ISSUE TITLE
New Upload Destination (Optimodo)

### ISSUE THREAD

**Issue by antoinne85** [eivindveg/HotSUploader#25]
Hey, everyone.

I've been working on a site called Optimodo, which features a tool called DraftMachine.

DraftMachine uses machine learning and optimization to help make good team selections for draft scenarios like Hero League by analyzing historical matchups.

The website is http://www.optimodo.com.

I've got a pull request ready for HotSUploader that I'll be submitting momentarily. Please take a look at the site (there's not much content as of yet, just DraftMachine) and let us know what you think.

Associated PR: #26

**Comment by eivindveg** [comment]
This is interesting. I'll get working on a UI design to split the views soon!

**Comment by eivindveg** [comment]
Beginning work on this now! =)

**Comment by antoinne85** [comment]
Sweet! Let me know if there's anything I can do to help.
It's been a long time since I've written any Java, but I'll do what I can.

**Comment by eivindveg** [comment]
I should be fine. Will mock up some "designs" in SceneBuilder and post screenshots here for feedback. Seems I'll need a logo designer, but unsure if I have any of those handy.

**Comment by eivindveg** [comment]
Apparently I'm an idiot. I don't see any way a release with multiprovider setups can be done without major restructuring(2.0). Will get the stuff I have slated for 1.2 done before I start changing everything around.

**Comment by antoinne85** [comment]
What's the roadblock? It looks like in UploadTask it's already prepared to ship the file off to multiple providers (it loops over them). 

I haven't spent too much time with the code as of yet, so I might be way off. 

I suppose it's also possible that there's an issue with resolving the status if one provider fails and one succeeds.

**Comment by eivindveg** [comment]
Not obscenely major, but I need to split up the architecture of FileHandler.java so that it has one fileMap per provider. That part is simple, but I'm also going to drop most of the runtime references(uploaded will be only a counter). After that, HomeController.java needs to blow up a tab for each provider.

Once I get all this in, I'm gonna just drop the current file store and redo it, but I want the models to be done right at that point. Essentially, I think my dream of the multi-provider friendly app requires significant reworking of both the HomeController and the FileHandler, in addition to many of the support classes.

**Comment by eivindveg** [comment]
To add: most of this stuff was hacked together in a few days, and the memory usage shows it.

**Comment by eivindveg** [comment]
Getting close to being able to sweetly integrate multiple providers in one gui. I've noticed that Hero.GG hasn't seen a single match from me since late June, and I'm striking it off the list. That leaves Optimodo as the only other provider I know of for which support is pending. Is this a website that actually sees marginal usage?

**Comment by eivindveg** [comment]
As per [a Strawpoll](http://strawpoll.me/5814678/r), most users don't want multiple providers, nor does your provider seem active. Closing this.
