### ISSUE TITLE
Version 2.1 Roadmap

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#79]
Discussion issue for 2.1 features and changes.

**Comment by eivindveg** [comment]
We currently do very little to handle exceptions, both on the information side as well as recovery. This should be the prime focus of 2.1.0

**Comment by zhedar** [comment]
That's what I thought, when I came here. We should probably log to a file as well, so we can just look exceptions up more easily.

**Comment by zhedar** [comment]
As we introduced the parser in 2.0, we should think about adding another thread / service, which parses the replays and checks the hash at the HOTSLogs API. We could also use several threads in parallel, because the API calls don't require that much bandwidth / execution time.
Then have another one, which does the actual uploading. Only uploading one file at a time makes sense, but maybe we can speed the whole process up, by doing the less heavy work in the background.
